name: Update data

on:
  schedule:
    - cron: '*/4 * * * *'

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python web_scraper.py
