name: Update data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered to update the data at 2am."
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: python web_scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update CSV file [skip ci]"
          git push -u origin main
