name: Update data

on:
  schedule:
    - cron: '* 7 * * *'
  workflow_dispatch:


jobs:
  update-csv:
    runs-on: ubuntu-latest

    env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python web_scraper.py
        
      - name: Debugging Information
        run: |
          echo "GH_TOKEN: $GH_TOKEN"
          env
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data file [skip ci]"
          git push -u origin main
